### ISSUE TITLE
模块解析错误

### ISSUE THREAD

**Issue by wa-monster** [x-shadow-x/tinymce-imageupload#3]
![image](https://user-images.githubusercontent.com/32135399/65415250-f65ea780-de27-11e9-886f-de572ae94d4f.png)
没懂具体是什么，我把reset符号去除 直接用 options,这里好了，然后报 ...headers哪里解析不了，没看懂这个地方怎么错了，headers也没找到具体的变量

**Comment by wa-monster** [comment]
options是main.js 121行  ...headers 是134行  tinymce是4.9.6

**Comment by x-shadow-x** [comment]
项目有po到github么~给下链接

**Comment by wa-monster** [comment]
> 项目有po到github么~给下链接

不好意思项目在公司，我回家了，明天发你吧，东西是我的项目里的yangwebsite，不过今天的还没push上去

**Comment by wa-monster** [comment]
已经传上去了，引入的在NewNote组件，路由是http://localhost:8080/#/Manager/new-note

**Comment by x-shadow-x** [comment]
npm包里使用了es6的扩展运算符，当时在vue-cli3生成的项目中测试是可以的。
已经重新上传es5版本的包，重新下载一下，1.0.7
